### ISSUE TITLE
test: 16bits image

### ISSUE THREAD

**Issue by Bueryoung** [chaoren88/DeamNet#4]
Is this project available to process 16bits 1channel image?
Do u ever have this attempt?

**Comment by wesl2** [comment]
> Is this project available to process 16bits 1channel image? Do u ever have this attempt?

Have you tested this type of picture? Is it effective? @Bueryoung

**Comment by Bueryoung** [comment]
tested， not that effective for me

**Comment by Bueryoung** [comment]
> > Is this project available to process 16bits 1channel image? Do u ever have this attempt?
> 
> Have you tested this type of picture? Is it effective? @Bueryoung


tested， not that effective for me
